# Generated by Django 5.2rc1 on 2025-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("paid", "Оплачено"),
                    ("unpaid", "Не оплачено"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
