# Generated by Django 5.2 on 2025-04-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="last_updated",
            new_name="updated_at",
        ),
    ]
